//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad
{
    using System;
    using System.Collections.Generic;
    
    public partial class заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public заказ()
        {
            this.Товар_Заказ = new HashSet<Товар_Заказ>();
        }
    
        public int idзаказ { get; set; }
        public int idклиент { get; set; }
        public int ВидОплаты { get; set; }
        public System.DateTime датасоставления { get; set; }
        public Nullable<decimal> общаясумма { get; set; }
    
        public virtual ВидОплаты ВидОплаты1 { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товар_Заказ> Товар_Заказ { get; set; }
    }
}
